apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-os-detector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-os-detector-binding
subjects:
- kind: ServiceAccount
  name: image-os-detector
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: image-os-detector
spec:
  serviceAccountName: image-os-detector
  containers:
  - name: os-detector
    image: localhost:5000/os-detector:v2  # Replace with your built image
  restartPolicy: Never